replicaCount: 1
image:
  repository: "ghcr.io/dklkv"
  tag: "v1.3.1-87d98e2"
  os: linux
  arch: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
  value: NzM4MDA2NDQ4NjpBQUVGaWlNUWhCREw4eFp5cmhmN21hUjk1WUtVdEJfazBfUQ==
securityContext:
  privileged: true
